### ISSUE TITLE
from script/console run_later errors on nil.context_path

### ISSUE THREAD

**Issue by prezently** [trinidad/trinidad_scheduler_extension#2]
I seem to be missing something with how to run the TrinidadScheduler. I'm running trinidad_scheduler_extension(0.1.1) and trying to use the run_later method. Running in a jruby rails app I go into "rails console" and try the following:

``` ruby
begin
  TrinidadScheduler.run_later do
    _logger.info "I am inside this block" #=> prints "I am inside this block" 
  end
rescue => e
  puts e.message
end
# prints : undefined method `context_path' for nil:NilClass
```

First of all, one frustrating thing is that I can't get at the real exception since it's being wrapped by JobError. Wrapping like that looks like it swallows the original stack trace and only saves the original exception message.

It seems unclear what needs to be done here to define context (which is what I'm assuming context_path is attempting to be called on. Any suggestions? In my trinidad config I'm already setting context_path to "/".

**Comment by prezently** [comment]
I hacked the AppJob class to remove the JobError wrapper and I can see that the error is occurring at trinidad_scheduler.rb:62 which traces back to app_job.rb:9 where there is a reference to a $servlet_context variable. 

So... I need to figure out how to make sure the $servlet_context is initialized...

**Comment by abrandoned** [comment]
I will drop the JobError wrapper out for the next patch, don't remember why I did that to begin with.  

Also, this will not run in console, it requires Trinidad to be running; running "rails console" or "rails c #{Rails.env}" runs the rails application through a local driver, not through trinidad.  The $servlet_context global is provided by jruby-rack when trinidad mounts the application as a rack app through jruby.  It will not be present without the application server running the app.

**Comment by prezently** [comment]
Hey, thanks a lot for the quick reply. I'm sorry my tone was so pissy in my first two comments on this issue, I was feel a bit overwhelmed with some work I have on my plate.

Regarding the JobError wrapper, as an API user I love it when applications use their own exception classes, it's nice to have API-specific exceptions to rescue so the client code can do different things in their rescue block if it's a JobError versus some other type of error. However, rather than rescue Exception and re-wrap as JobError, IMO, the better approach is to add that API-specificity at the time of exception raising rather than rescuing. The problem with wrapping, especially at the level of Exception (vs, say, StandardError), is that users of your API will have trouble adding their own rescue blocks for things like SystemExit. At the very least, if you do have good reason to wrap all exceptions, I'd suggest making the wrapped exception object available from your wrapper class with a #original_exception method or something like that.

Anyways, thanks again for the help.

-Andrew
