### ISSUE TITLE
can run without trinidad?

### ISSUE THREAD

**Issue by francescoagati** [trinidad/trinidad_scheduler_extension#3]
Is possible running scheduler extension without trinidad ?

**Comment by abrandoned** [comment]
If you are not using trinidad then I would use a different scheduling gem (rufus-scheduler) or Quartz directly.  This specific gem is built to run inside of Trinidad and utilizes servlet context and lifecycle extensions offered through Trinidad.  

If I didn't understand the question then let me know.

Thanks, bsd

**Comment by francescoagati** [comment]
i like to use this gem inside a rails application with tomcat without trinidad. But using a war file create with warbler.
Trinidad can be used inside a war file in tomcat?

**Comment by abrandoned** [comment]
This gem is specifically for a Trinidad extension, it relies on the trinidad startup sequence and extension hooks to fire the events to start the scheduler.

While it currently doesn't support a Warbler implementation I am confident that a similar gem could be built using the same structure/code (outside of the trinidad specific startup stuff).  If you decide to do that then let me know and I will help where/when I can.  

You can also use the servlet container initialization hook for Quartz and a custom web.xml in Warbler to achieve a similar outcome with a war deployed app.  

http://quartz-scheduler.org/documentation/quartz-2.x/cookbook/ServletInitScheduler
http://kenai.com/projects/warbler/pages/Home

Personally, I spent a good amount of time dealing with .war deployments and rails apps and eventually just ported everything I needed to Trinidad.

Thanks, bsd
