### ISSUE TITLE
Problem merging config opts with the default options

### ISSUE THREAD

**Issue by zszugyi** [trinidad/trinidad_scheduler_extension#5]
I'm running into a problem with a rails app when  specifying the thread_count option in config/trinidad.yml
After some debugging, it seems like that the file is correctly read and the options are passed to the extension.
When I add some "logging" to trinidad_scheduler.rb#quartz_scheduler (line 99), it looks like the merging
goes sideways:

``` ruby
opts: {:thread_count=>3}
options: {:wrapped=>false, :thread_count=>10, :thread_priority=>5, :thread_count=>3}
```

Notice the duplicate key "thread_count". I couldn't reproduce this Hash#merge! behavior outside of
this gem, so this is likely not an issue with JRuby or Rails. Also tried using Hash#merge instead of merge!
without success.

Here's the relevant part of the trinidad.yml:

``` yml

---
  ... other options
  extensions:
    scheduler:
      thread_count: 3
```

Environment:
rails 3.1.3
jruby 1.6.7 (ruby-1.9.2-p312) (2012-02-22 3e82bc8) (Java HotSpot(TM) 64-Bit Server VM 1.7.0) Windows 7-amd64-java
(also reproduced the same issue on linux)
trinidad 1.3.4
trinidad_scheduler_extension 0.1.2

**Comment by zszugyi** [comment]
I've been investigating this a bit more. The 2 :thread_count symbols in options have different hash codes.

**Comment by kares** [comment]
you should be able to test the fix out with bundle using :

```
gem 'trinidad', :require => nil
gem "trinidad_scheduler_extension", :require => nil, :git => "git://github.com/trinidad/trinidad_scheduler_extension.git"
```

(don't forget to `bundle exec trinidad`) let us know and thanks for reporting !

**Comment by zszugyi** [comment]
Great, thank you for looking into this! Will try it when I get a chance.

**Comment by zszugyi** [comment]
That fixed it for me, thank you!
